# Used to create unique IDs
import uuid

# Yes the above library provides a chance of collision. However, it is extremely unlikely and we can
# use the names, email, and phone to resolve collisions

class User:
    """
    Represents a user in the ticketing system.
    -----------------------------------------------------------------------------
    | Attributes:
    |- first_name : str
    |   First name of the user
    |- last_name : str
    |   Last name of the user
    |- email : str (optional)
    |   A place to store the user's email address but is optional for the user
    |- phone : str (optional)
    |   A place to store the user's phone number but is optional for the user
    |- user_id : str
    |   A unique identifier generated by this program to use in the ticket
    |   (This will be unique to every user)
    """

    # Initializing the User
    def __init__(self, first_name: str, last_name: str, email: str = None, phone: str = None):
      ## using underscores to make everything somewhat private
      ## convention I discovered online
      self.__first_name = first_name
      self.__last_name = last_name
      self.__email = email
      self.__phone = phone
      self.__user_id = uuid.uuid4()

    # A string representation of the user
    def __str__(self):
      return (
          f"First Name: {self.__first_name}\n"
          f"Last Name: {self.__last_name}\n"
          f"User ID: {self.__user_id}\n"
          f"Email: {self.__email is not None}\n"
          f"Phone: {self.__phone is not None}\n"
      )

    # Accessor methods
    def get_first_name(self) -> str:
      return self.__first_name
    def get_last_name(self) -> str:
      return self.__last_name
    def get_email(self) -> str:
      return self.__email
    def get_phone(self) -> str:
      return self.__phone